version: '3'

services:
  mysql:
    container_name: primary_mysql
    restart: always
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: blueviolet
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/docker-entrypoint-initdb.d