POST http://localhost:8080/api/admin/v1/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXJAdGVzdC5jb20iLCJ1c2VySWQiOjEsImV4cCI6MTcxNTU5NTYwMH0.xqHTVu0pzyusSOE-5TUwprtyeVexe4Q2dzduqi8rEB8

{
  "categories": [
    {
      "name": "남성",
      "level": 1,
      "categoryKey": "11",
      "parentCategoryKey": null
    },
    {
      "name": "상의",
      "level": 2,
      "categoryKey": "21",
      "parentCategoryKey": "11"
    },
    {
      "name": "반소매 티셔츠",
      "level": 3,
      "categoryKey": "31",
      "parentCategoryKey": "21"
    }
  ]
}
