GET http://localhost:8080/api/admin/v1/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXJAdGVzdC5jb20iLCJ1c2VySWQiOjEsImV4cCI6MTcxOTM4ODM4OX0.6_FgFAqVMC0vLYxE1DxPzFVb1KoXAnv_w6DBsy-uyAs
